# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibo_list = [], ans = 0, prev = 1, current = 1

until ans > 4000000
  ans = prev + current
  prev = current
  current = ans
  fibo_list.push ans
end

fibo_list.pop

p fibo_list.reduce {|sum, item|
  item = 0 unless item.even?
  sum + item
}

# ruby ruby/002.rb  0.09s user 0.07s system 85% cpu 0.186 total
